import type { Metadata } from "next";
import {Montserrat } from "next/font/google";
import "../globals.css";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import SocialFab from "../../components/ui/SocialFab";
import "../../lib/i18n";
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <SocialFab/>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
